export enum StudioInputsProtobuf {
  STUDIO_INPUT_UNSET = 0,
  STUDIO_INPUT_SELECT = 1,
  STUDIO_INPUT_SELECT_MULTI = 2,
  STUDIO_INPUT_TIME_MINUTES = 3,
  STUDIO_INPUT_STRING = 4,
  STUDIO_INPUT_NUMBER = 5,
  STUDIO_INPUT_POINTS = 6
}
